schema_version = "1.0.0"

id = "nolimits2_utilities"
version = "0.2.0"
name = "NoLimits 2 Utilities"
tagline = "Utilities for NoLimits 2, track import and more"
maintainer = "Ercan Akyürek <ercan.akyuerek@gmail.com>"
type = "add-on"
website = "https://github.com/geforcefan/blender-nolimits2-utilities"
copyright = ["2026 Ercan Akyürek"]
blender_version_min = "5.1.0"
license = ["SPDX:GPL-3.0-or-later"]
tags = ["Import-Export"]

[build]
paths_exclude_pattern = ["__pycache__/", "/.*", "*.pyc", "/build/", "/dev/", "/dist/", "/docs/", "/tests/", "/pyproject.toml"]
