schema_version = "1.0.0"

id = "dev"
version = "0.1.0"
name = "NoLimits 2 Utilities Dev"
tagline = "Throwaway tools while developing the utilities"
maintainer = "Ercan Akyürek <ercan.akyuerek@gmail.com>"
type = "add-on"
website = "https://github.com/geforcefan/blender-nolimits2-utilities"
copyright = ["2026 Ercan Akyürek"]
blender_version_min = "5.1.0"
license = ["SPDX:GPL-3.0-or-later"]
tags = ["Development"]

[build]
paths_exclude_pattern = ["__pycache__/", "/.*"]
